# Generated by Django 5.2.16 on 2026-07-31 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('custo_producao_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_producao', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_producao', to='catalog.variacaoproduto')),
            ],
            options={
                'verbose_name': 'lote de produção',
                'verbose_name_plural': 'lotes de produção',
                'ordering': ['-data_producao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste')], max_length=10)),
                ('origem', models.CharField(choices=[('venda', 'Venda'), ('producao', 'Produção'), ('compra', 'Compra'), ('devolucao', 'Devolução'), ('ajuste', 'Ajuste manual')], max_length=12)),
                ('quantidade', models.IntegerField(help_text='Positivo para entrada, negativo para saída.')),
                ('saldo_resultante', models.IntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('lote_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='inventory.loteproducao')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='suppliers.pedidocomprafornecedor')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='catalog.variacaoproduto')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variacao', '-created_at'], name='inventory_m_variaca_498419_idx')],
            },
        ),
    ]
