# Generated by Django 5.2.17 on 2026-08-20 19:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_categoria_options_categoria_destaque_and_more'),
        ('orders', '0002_pedido_canal_pedido_desconto_manual_pedido_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstoque',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('expira_em', models.DateTimeField(db_index=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='orders.pedido')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='catalog.variacaoproduto')),
            ],
            options={
                'verbose_name': 'reserva de estoque',
                'verbose_name_plural': 'reservas de estoque',
                'indexes': [models.Index(fields=['variacao', 'expira_em'], name='orders_rese_variaca_02450d_idx')],
            },
        ),
    ]
