# Generated by Django 5.2.17 on 2026-08-20 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_email', models.CharField(blank=True, db_index=True, max_length=254)),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('usuario_papel', models.CharField(blank=True, max_length=15)),
                ('acao', models.CharField(choices=[('criar', 'Criação'), ('atualizar', 'Alteração'), ('excluir', 'Exclusão'), ('login', 'Login'), ('logout', 'Logout'), ('ajuste_estoque', 'Ajuste de estoque'), ('mudanca_status', 'Mudança de status de pedido'), ('abertura_caixa', 'Abertura de caixa'), ('fechamento_caixa', 'Fechamento de caixa'), ('sangria', 'Sangria'), ('suprimento', 'Suprimento'), ('venda', 'Venda no PDV'), ('cancelamento_venda', 'Cancelamento de venda'), ('devolucao', 'Devolução'), ('pagamento_conta', 'Baixa de conta a pagar'), ('alteracao_preco', 'Alteração de preço'), ('reset_senha', 'Redefinição de senha por admin'), ('mudanca_papel', 'Mudança de papel'), ('desativar_usuario', 'Desativação de usuário'), ('reativar_usuario', 'Reativação de usuário')], db_index=True, max_length=25)),
                ('nivel', models.CharField(choices=[('info', 'Informativo'), ('atencao', 'Atenção'), ('critico', 'Crítico')], db_index=True, default='info', max_length=10)),
                ('app_label', models.CharField(blank=True, db_index=True, max_length=50)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('objeto_repr', models.CharField(blank=True, help_text='Descrição legível, congelada no momento do registro.', max_length=200)),
                ('descricao', models.CharField(blank=True, help_text='Frase pronta para a tela, sem precisar interpretar o JSON.', max_length=255)),
                ('dados', models.JSONField(blank=True, default=dict, help_text='Diff {campo: {de, para}} ou payload da ação de negócio.')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_data_idx'), models.Index(fields=['usuario', '-created_at'], name='audit_usuario_idx'), models.Index(fields=['app_label', 'model_name', 'objeto_id', '-created_at'], name='audit_objeto_idx'), models.Index(fields=['acao', '-created_at'], name='audit_acao_idx'), models.Index(fields=['nivel', '-created_at'], name='audit_nivel_idx')],
            },
        ),
    ]
