# Generated by Django 5.2.16 on 2026-07-31 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='catalog.categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_origem', models.CharField(choices=[('producao_propria', 'Produção própria'), ('revenda', 'Revenda')], default='revenda', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('aprovada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TabelaMedidas',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_medidas', to='catalog.categoria')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_medidas', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'tabela de medidas',
                'verbose_name_plural': 'tabelas de medidas',
            },
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=60)),
                ('tamanho', models.CharField(blank=True, max_length=30)),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_gramas', models.PositiveIntegerField(blank=True, null=True)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('largura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('profundidade_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalog.produto')),
            ],
            options={
                'verbose_name': 'variação de produto',
                'verbose_name_plural': 'variações de produto',
                'ordering': ['produto', 'tamanho', 'cor'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('url_externa', models.URLField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalog.variacaoproduto')),
            ],
            options={
                'verbose_name': 'imagem de produto',
                'verbose_name_plural': 'imagens de produto',
                'ordering': ['variacao', 'ordem'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'ativo'], name='catalog_pro_categor_1718ca_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['tipo_origem'], name='catalog_pro_tipo_or_cfc8da_idx'),
        ),
        migrations.AddConstraint(
            model_name='avaliacao',
            constraint=models.UniqueConstraint(fields=('produto', 'cliente'), name='uniq_avaliacao_produto_cliente'),
        ),
        migrations.AddConstraint(
            model_name='variacaoproduto',
            constraint=models.UniqueConstraint(fields=('produto', 'cor', 'tamanho'), name='uniq_variacao_produto_cor_tamanho'),
        ),
    ]
