# Generated by Django 5.2.16 on 2026-07-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacaoproduto',
            name='custo_medio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo de referência do SKU, usado no relatório de margem.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variacaoproduto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Abaixo deste saldo, o SKU entra no alerta de estoque baixo.'),
        ),
    ]
