# Generated by Django 5.2.16 on 2026-07-31 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('contato_nome', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('prazo_medio_entrega_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompraFornecedor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('confirmado', 'Confirmado'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='rascunho', max_length=15)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('observacoes', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='suppliers.fornecedor')),
            ],
            options={
                'verbose_name': 'pedido de compra',
                'verbose_name_plural': 'pedidos de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='catalog.variacaoproduto')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suppliers.pedidocomprafornecedor')),
            ],
            options={
                'verbose_name': 'item de pedido de compra',
                'verbose_name_plural': 'itens de pedido de compra',
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('vencimento', models.DateField()),
                ('pago_em', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=12)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='suppliers.fornecedor')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='suppliers.pedidocomprafornecedor')),
            ],
            options={
                'verbose_name': 'conta a pagar',
                'verbose_name_plural': 'contas a pagar',
                'ordering': ['vencimento'],
            },
        ),
    ]
