# Generated by Django 5.2.16 on 2026-07-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
