# Generated by Django 5.2.16 on 2026-08-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_fornecedor_bairro_fornecedor_cep_fornecedor_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='categoria',
            field=models.CharField(choices=[('mercadoria', 'Mercadoria / fornecedor'), ('aluguel', 'Aluguel'), ('energia', 'Energia elétrica'), ('agua', 'Água'), ('telecom', 'Internet e telefone'), ('impostos', 'Impostos e taxas'), ('salarios', 'Salários e encargos'), ('marketing', 'Marketing'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], db_index=True, default='outros', max_length=12),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='conta_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeticoes', to='suppliers.contapagar'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='recorrente',
            field=models.BooleanField(default=False, help_text='Ao pagar, lança automaticamente a conta do mês seguinte.'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='suppliers.fornecedor'),
        ),
    ]
