# Generated by Django 5.2.16 on 2026-07-31 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_loja', models.CharField(default='Samara Beach', max_length=120)),
                ('cor_primaria', models.CharField(default='#0891b2', help_text='Cor principal (botões, links, destaques de marca).', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida, ex.: #0891b2.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('cor_secundaria', models.CharField(default='#0e7490', help_text='Variante escura da primária (hover).', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida, ex.: #0891b2.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('cor_destaque', models.CharField(default='#fb7185', help_text='Cor de destaque/CTA (ex.: coral).', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida, ex.: #0891b2.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('cor_fundo', models.CharField(default='#f5efe6', help_text='Cor de fundo suave (areia).', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida, ex.: #0891b2.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('cor_texto', models.CharField(default='#1f2937', help_text='Cor de texto principal.', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal válida, ex.: #0891b2.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'identidade visual',
                'verbose_name_plural': 'identidade visual',
            },
        ),
    ]
