# Generated by Django 5.2.16 on 2026-08-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número com DDI e DDD, ex.: 5511999998888.', max_length=20),
        ),
    ]
