# Generated by Django 5.2.16 on 2026-08-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_branding_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='hero_badge',
            field=models.CharField(blank=True, default='Nova coleção de verão', max_length=80),
        ),
        migrations.AddField(
            model_name='branding',
            name='hero_cta_link',
            field=models.CharField(blank=True, default='/produtos', max_length=300),
        ),
        migrations.AddField(
            model_name='branding',
            name='hero_cta_texto',
            field=models.CharField(blank=True, default='Ver coleção', max_length=40),
        ),
        migrations.AddField(
            model_name='branding',
            name='hero_imagem',
            field=models.ImageField(blank=True, help_text='Imagem de fundo (modo foto) ou banner pronto (modo banner).', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='branding',
            name='hero_imagem_link',
            field=models.CharField(blank=True, help_text='Para onde o banner leva ao clicar (modo banner). Ex.: /produtos', max_length=300),
        ),
        migrations.AddField(
            model_name='branding',
            name='hero_modo',
            field=models.CharField(choices=[('texto', 'Somente textos'), ('foto', 'Foto de fundo + textos'), ('banner', 'Banner pronto (só imagem)')], default='foto', help_text='Como o topo da loja é exibido.', max_length=10),
        ),
        migrations.AddField(
            model_name='branding',
            name='hero_subtitulo',
            field=models.TextField(blank=True, default='Biquínis, maiôs, saídas e acessórios — com produção própria e curadoria especial. Encontre o seu look à beira-mar.'),
        ),
        migrations.AddField(
            model_name='branding',
            name='hero_titulo',
            field=models.CharField(blank=True, default='Moda praia que combina com o seu verão.', max_length=160),
        ),
    ]
