# Generated by Django 5.2.16 on 2026-08-06 18:01

import apps.company.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(blank=True, help_text='Nome registrado na Receita Federal.', max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome usado no dia a dia (aparece no recibo).', max_length=200)),
                ('cnpj', models.CharField(blank=True, help_text='Somente números ou com máscara.', max_length=18, validators=[apps.company.models.validar_cnpj])),
                ('inscricao_estadual', models.CharField(blank=True, help_text='Deixe vazio ou "ISENTO" quando não houver.', max_length=20)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20)),
                ('regime_tributario', models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real'), ('mei', 'MEI')], max_length=12)),
                ('cep', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='Informe um CEP válido, ex.: 62000-000.', regex='^\\d{5}-?\\d{3}$')])),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='Com DDI e DDD, ex.: 5585999998888.', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, help_text='Só o usuário, sem @ e sem URL.', max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('tiktok', models.CharField(blank=True, max_length=100)),
                ('horario_funcionamento', models.TextField(blank=True, help_text='Ex.: Seg a Sex 9h-18h, Sáb 9h-13h.')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresa',
            },
        ),
    ]
