# Generated by Django 5.2.16 on 2026-07-31 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transportadora', models.CharField(blank=True, max_length=80)),
                ('servico', models.CharField(blank=True, max_length=80)),
                ('codigo_rastreio', models.CharField(blank=True, db_index=True, max_length=60)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('postado', 'Postado'), ('em_transito', 'Em trânsito'), ('entregue', 'Entregue'), ('devolvido', 'Devolvido')], default='pendente', max_length=12)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('postado_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='envio', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'envio',
                'verbose_name_plural': 'envios',
                'ordering': ['-created_at'],
            },
        ),
    ]
