# Generated by Django 5.2.16 on 2026-08-01 00:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_pedido_canal_pedido_desconto_manual_pedido_vendedor_and_more'),
        ('payments', '0002_pagamento_parcelas_pagamento_troco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCaixa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], db_index=True, default='aberta', max_length=10)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, help_text='Troco inicial deixado na gaveta.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_fechamento_informado', models.DecimalField(blank=True, decimal_places=2, help_text='Dinheiro contado na gaveta ao fechar.', max_digits=12, null=True)),
                ('valor_fechamento_esperado', models.DecimalField(blank=True, decimal_places=2, help_text='Quanto o sistema calculou que deveria haver em espécie.', max_digits=12, null=True)),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, help_text='Informado − esperado: positivo é sobra, negativo é falta.', max_digits=12, null=True)),
                ('observacoes_abertura', models.TextField(blank=True)),
                ('observacoes_fechamento', models.TextField(blank=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sessão de caixa',
                'verbose_name_plural': 'sessões de caixa',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('abertura', 'Abertura'), ('venda', 'Venda'), ('sangria', 'Sangria'), ('suprimento', 'Suprimento'), ('devolucao', 'Devolução')], max_length=12)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='payments.pagamento')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa', to='orders.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa', to=settings.AUTH_USER_MODEL)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='pos.sessaocaixa')),
            ],
            options={
                'verbose_name': 'movimento de caixa',
                'verbose_name_plural': 'movimentos de caixa',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessaocaixa',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aberta')), fields=('operador',), name='uma_sessao_aberta_por_operador'),
        ),
        migrations.AddIndex(
            model_name='movimentocaixa',
            index=models.Index(fields=['sessao', 'created_at'], name='pos_movimen_sessao__1f8361_idx'),
        ),
    ]
