# Generated by Django 5.2.16 on 2026-08-01 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pedido_canal_pedido_desconto_manual_pedido_vendedor_and_more'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentocaixa',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('devolucao', 'Devolução (dinheiro de volta)'), ('troca', 'Troca por outro produto')], max_length=10)),
                ('motivo', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credito_usado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedido_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='orders.pedido')),
                ('pedido_troca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_consumidas', to='orders.pedido')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='pos.sessaocaixa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'devolução',
                'verbose_name_plural': 'devoluções',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pos.devolucao')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='orders.itempedido')),
            ],
            options={
                'verbose_name': 'item devolvido',
                'verbose_name_plural': 'itens devolvidos',
            },
        ),
    ]
