# Generated by Django 5.2.16 on 2026-07-31 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(blank=True, max_length=40)),
                ('metodo', models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao', 'Cartão'), ('boleto', 'Boleto')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payload_webhook', models.JSONField(blank=True, default=dict)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
