# Generated by Django 5.2.16 on 2026-08-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='parcelas',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='troco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('dinheiro', 'Dinheiro'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito')], max_length=10),
        ),
    ]
