# Generated by Django 5.2.16 on 2026-08-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pagamento_parcelas_pagamento_troco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao', 'Cartão'), ('boleto', 'Boleto'), ('dinheiro', 'Dinheiro'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito'), ('credito_troca', 'Crédito de troca')], max_length=15),
        ),
    ]
